format = "$custom$directory$git_branch$git_commit$git_status[âœ ](white)"
add_newline = false

[directory]
truncation_length = 1
format = "[$path](bold blue)"

[git_branch]
only_attached = true
format = "[\\(](white)[$branch](yellow)"

[git_commit]
only_detached = true
format = "[ \\(](white)[$hash](yellow)"

[git_status]
format = "$ahead_behind[\\)](white)$all_status"

ahead = "[â†‘${count}](bold cyan)"
behind = "[â†“${count}](bold cyan)"
diverged = "[â†‘${ahead_count}â†“${behind_count}](bold cyan)"

conflicted = "[ğ™ ](bold red)"
untracked = "[âš‘ ](red)"
stashed = "[â¬š ](white)"
staged = "[â™» ](green)"
modified = "[â™» ](red)"
renamed = ""
deleted = "[âœ– ](red)"

[custom.host_icon]
command = "echo $MY_HOST_ICON"
when = "true"
format = "[$output](white) "